version: 1.0.{build}

image:
- Visual Studio 2019

branches:
  only:
    - ci

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
  package_version: $(APPVEYOR_BUILD_VERSION)


build_script:
  - cmd: echo Start build script
  - cmd: dotnet build Git\Git.csproj
  - cmd: dotnet pack Git\Git.csproj -o Packages
  - cmd: dotnet build ShellRunner\Shell.csproj
  - cmd: dotnet pack ShellRunner\Shell.csproj -o Packages

artifacts:
- path: 'Packages\*.nupkg'

deploy:
  - provider: NuGet  
    api_key:
      secure: 2pajrRY2CavGFpYQNxvqVH989FUv3pRa2oKTB6Ar9Fb45obCmBzBqoeJrkp3+nrx
    skip_symbols: false
    artifact: /.*\.nupkg/